server:
  port: 8080
  servlet:
    context-path: /graduate-insights/v1/api
spring:
  application:
    name: graduate-insights-api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/graduate_insights
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  sql:
    init:
      mode: always
      schema-locations: classpath:tables.sql
      data-locations: classpath:inserts.sql
  mail:
    host: smtp.gmail.com
    port: 587
    username: garlee016@gmail.com
    password: azejzfwfshvwdiok
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2000
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 24 horas
      refresh-token:
        expiration: 604800000 # 7 días

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  file:
    upload-dir: ./uploads/cv

logging:
  level:
    root: INFO
    pe.com.graduate.insights.api: DEBUG
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error
