server:
  port: 8080
  servlet:
    context-path: /graduate-insights/v1/api
spring:
  application:
    name: graduate-insights-api
  datasource:
    url: jdbc:mysql://localhost:3306/graduate_insights
    username: root
    password: abcd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  sql:
    init:
      mode: always
      schema-locations: classpath:tables.sql
      data-locations: classpath:inserts.sql

  mail:
    host: smtp.gmail.com
    port: 587
    username: admin@coneicucayali.org
    password: ejpuofhrojsmvwbw
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2000
          starttls:
            enable: true

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    enabled: true
    path: "/index.html"

logging:
  level:
    root: INFO

